version: '3'

services:
  api:
    image: backend
    build: ./api
    ports:
      - "5000:5000"
  web:
    image: node:14
    build: ./www
    ports:
      - "80:80"
    environment:
      - API_ENDPOINT=http://api:5000/api/
    
    command: ["npm", "start"]
